name: leaf_disease_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.11.0+2
  copy_with_extension_gen: ^5.0.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  image: ^4.3.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  pytorch_lite: ^4.3.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/models/classification/
    - assets/models/detection/
